adminCategories_index:
    path:     /
    defaults: { _controller: "MickwebEcommerceBundle:CategoryAdmin:index" }
    methods:  GET

adminCategories_show:
    path:     /{id}/show
    defaults: { _controller: "MickwebEcommerceBundle:CategoryAdmin:show" }
    methods:  GET

adminCategories_new:
    path:     /new
    defaults: { _controller: "MickwebEcommerceBundle:CategoryAdmin:new" }
    methods:  [GET, POST]

adminCategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "MickwebEcommerceBundle:CategoryAdmin:edit" }
    methods:  [GET, POST]

adminCategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "MickwebEcommerceBundle:CategoryAdmin:delete" }
    methods:  DELETE
