mickweb_ecommerce:
    resource: "@MickwebEcommerceBundle/Resources/config/routing.yml"
    prefix:   /accueil #permet de ne pas remettre à chaque fois /accueil dans chacune des routes

mick_website:
    resource: "@MickWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: MickwebUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
