<?php

namespace Mickweb\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        return $this
                    ->createQueryBuilder('p')
                    ->getQuery()
                    ->getResult()
        ;
    }

    public function byCategorie($categories)
    {
        $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.categories = :categories')
                    ->andWhere('u.disponible = 1') // prend seulement les pdts disponibles
                    ->orderBy('u.id')
                    ->setParameter('categories', $categories);
        return $qb->getQuery()->getResult();
    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.id IN (:array)')
                    ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.nom like :chaine')
                    ->andWhere('u.disponible = 1') // prend seulement les pdts disponibles
                    ->orderBy('u.id')
                    ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }
}
