mickweb_ecommerce_homepage:
    path:     /
    # path:     /{page}
    defaults:
        _controller: MickwebEcommerceBundle:Product:index
        page:        1
    # requirements:
    #     page: \d*

mickweb_ecommerce_fiche_produit:
    path:     /fiche_produit/{id}
    defaults: 
        _controller: MickwebEcommerceBundle:Product:ficheProduit
    requirements:
        id: \d+

mickweb_ecommerce_ajout:
    path:     /ajout
    defaults: 
        _controller: MickwebEcommerceBundle:Product:ajout   

mickweb_ecommerce_modifier:
    path:     /modifier/{id}
    defaults: 
        _controller: MickwebEcommerceBundle:Product:modifier
    requirements:
        id: \d+

mickweb_ecommerce_supprimer:
    path:     /supprimer/{id}
    defaults: 
        _controller: MickwebEcommerceBundle:Product:supprimer
    requirements:
        id: \d+

mickweb_ecommerce_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: MickwebEcommerceBundle:Product:viewSlug
        format: html
    requirements:
        year: \d{4}
        format: html|xml

#################################################################
#                            CRUD Produits 

mickweb_product_adminProduct:
    resource: "@MickwebEcommerceBundle/Resources/config/routing/routingProductAdmin.yml"
    prefix:    /admin/product

#################################################################
#                            CRUD Categories 

mickweb_category_adminCategories:
    resource: "@MickwebEcommerceBundle/Resources/config/routing/routingCategoriesAdmin.yml"
    prefix:    /admin/categories

#################################################################
#                            Admin Commandes 

mickweb_commandes_adminCommandes:
    resource: "@MickwebEcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
    prefix:    /admin/commandes

#################################################################
#                            Panier 

ajouter_panier:
    path:    /ajouter/{id}
    defaults:
        _controller: MickwebEcommerceBundle:Panier:ajouter
    # requirements:
    #     id: \d+

supprimer_panier:
    path:    /supprimer/panier/{id}
    defaults:
        _controller: MickwebEcommerceBundle:Panier:supprimer

mickweb_ecommerce_panier:
    path:    /panier
    defaults:
        _controller: MickwebEcommerceBundle:Panier:panier
    # requirements:
    #     id: \d+

mickweb_ecommerce_livraison:
    path:    /livraison
    defaults:
        _controller: MickwebEcommerceBundle:Panier:livraison

mickweb_ecommerce_validation:
    path:    /validation
    defaults:
        _controller: MickwebEcommerceBundle:Panier:validation

mickweb_ecommerce_validation_commande:
    path:    /api/banque/{id}
    defaults:
        _controller: MickwebEcommerceBundle:Commandes:validationCommande

mickweb_ecommerce_livraisonAdresseSuppression:
    path:    /livraison/adresse/suppression/{id}
    defaults:
        _controller: MickwebEcommerceBundle:Panier:adresseSuppression

#################################################################
#                           Categories

categorieProduits:
    path:    /categorie/{categories}
    defaults:
        _controller: MickwebEcommerceBundle:Product:categorie

#################################################################
#                           Page de contacts

pageContacts:
    path:    /contacts
    defaults:
        _controller: MickwebEcommerceBundle:Product:contactForm

#################################################################
#                           Recherche

rechercheProduits:
    path:    /recherche
    defaults:
        _controller: MickwebEcommerceBundle:Product:rechercheTraitement
