services:
    setNewFacture:
      class: Mickweb\EcommerceBundle\Services\GetFacture
      arguments:
        - "@service_container" 

    setNewReference:
      class: Mickweb\EcommerceBundle\Services\GetReference
      arguments:
        - "@security.token_storage"
        - "@doctrine.orm.entity_manager"

    tva:
      class: Mickweb\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }
    montantTva:
      class: Mickweb\EcommerceBundle\Twig\Extension\MontantTvaExtension
      tags:
        - { name: twig.extension }

    redirectionListener:
      class: Mickweb\EcommerceBundle\Listener\RedirectionListener
      arguments:
        - "@service_container"
        - "@session"
        - "@security.token_storage"
      # arguments: ["@service_container","@session"]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#    mickweb_ecommerce.example:
#        class: Mickweb\EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
