services:
    tva:
      class: Mickweb\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }

#    mickweb_ecommerce.example:
#        class: Mickweb\EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
